#!/usr/bin/env node
/**
 * Generates workers/src/guides.ts from resources/*.txt
 * Bundles all guide text into a TypeScript module at build time.
 *
 * Run: node workers/scripts/gen-guides.js
 */

import { readFileSync, writeFileSync, readdirSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '../..')
const resourcesDir = join(root, 'resources')

const DISPLAY_NAMES = {
  'adult_heron_and_egret_rescue_and_care_-_google_docs.txt': 'Heron & Egret Rescue and Care',
  'animal_entangled___caught_in_fishing_line___fishing_hooks___fishing_tackle.txt': 'Entangled Animal Rescue',
  'bat_rescue_and_care.txt': 'Bat Rescue and Care',
  'bobcat_rescue_and_care.txt': 'Bobcat Rescue and Care',
  'coyote_rescue_and_care.txt': 'Coyote Rescue and Care',
  'deer_and_fawn_rescue_and_care.txt': 'Deer & Fawn Rescue and Care',
  'duck_and_goose_rescue_and_care.txt': 'Duck & Goose Rescue and Care',
  'fox_rescue_and_care.txt': 'Fox Rescue and Care',
  'gull_rescue_and_care.txt': 'Gull Rescue and Care',
  'hummingbird_rescue_and_care.txt': 'Hummingbird Rescue and Care',
  'opossum_rescue_and_care.txt': 'Opossum Rescue and Care',
  'raccoon_rescue_and_care.txt': 'Raccoon Rescue and Care',
  'raptor_rescue_and_care.txt': 'Raptor Rescue and Care',
  'raven_rescue_and_care.txt': 'Raven Rescue and Care',
  'rodent_rescue_and_care.txt': 'Rodent Rescue and Care',
  'skunk_rescue_and_care.txt': 'Skunk Rescue and Care',
  'snake_identification_and_rescue.txt': 'Snake Identification and Rescue',
  'songbird_rescue_and_care_guide.txt': 'Songbird Rescue and Care',
  'squirrel_rescue_and_care.txt': 'Squirrel Rescue and Care',
  'wild_turkey_rescue_and_care.txt': 'Wild Turkey Rescue and Care',
}

const CATEGORIES = {
  'bat_rescue_and_care.txt': 'mammal',
  'bobcat_rescue_and_care.txt': 'mammal',
  'coyote_rescue_and_care.txt': 'mammal',
  'deer_and_fawn_rescue_and_care.txt': 'mammal',
  'fox_rescue_and_care.txt': 'mammal',
  'opossum_rescue_and_care.txt': 'mammal',
  'raccoon_rescue_and_care.txt': 'mammal',
  'rodent_rescue_and_care.txt': 'mammal',
  'skunk_rescue_and_care.txt': 'mammal',
  'squirrel_rescue_and_care.txt': 'mammal',
  'adult_heron_and_egret_rescue_and_care_-_google_docs.txt': 'waterbird',
  'duck_and_goose_rescue_and_care.txt': 'waterbird',
  'gull_rescue_and_care.txt': 'waterbird',
  'raptor_rescue_and_care.txt': 'raptor',
  'raven_rescue_and_care.txt': 'songbird',
  'songbird_rescue_and_care_guide.txt': 'songbird',
  'hummingbird_rescue_and_care.txt': 'songbird',
  'snake_identification_and_rescue.txt': 'reptile',
  'wild_turkey_rescue_and_care.txt': 'gamebird',
  'animal_entangled___caught_in_fishing_line___fishing_hooks___fishing_tackle.txt': 'general',
}

const files = readdirSync(resourcesDir).filter(f => f.endsWith('.txt')).sort()

const guides = files.map(filename => {
  const text = readFileSync(join(resourcesDir, filename), 'utf8')
  return {
    filename,
    name: DISPLAY_NAMES[filename] || filename.replace(/_/g, ' ').replace('.txt', ''),
    category: CATEGORIES[filename] || 'general',
    text,
  }
})

const ts = `// AUTO-GENERATED by workers/scripts/gen-guides.js — do not edit
// Re-run: node workers/scripts/gen-guides.js

export interface Guide {
  filename: string
  name: string
  category: string
  text: string
}

export const BUILTIN_GUIDES: Guide[] = ${JSON.stringify(guides, null, 2)}
`

const outPath = join(__dirname, '../src/guides.ts')
writeFileSync(outPath, ts)
console.log(`✓ Generated workers/src/guides.ts (${guides.length} guides, ${Math.round(guides.reduce((a, g) => a + g.text.length, 0) / 1024)}KB)`)
