#!/usr/bin/env node
/**
 * Generates workers/src/guides.ts from resources/*.txt
 * Bundles all guide text into a TypeScript module at build time.
 *
 * Run: node workers/scripts/gen-guides.js
 */

import { readFileSync, writeFileSync, readdirSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '../..')
const resourcesDir = join(root, 'resources')

// Derive display-name and category lookups from the shared catalog. Catalog
// entries with filename: null (e.g. "Pigeon") aren't bundled here — they're
// catalog-only species without a dedicated guide. A guide_display_name
// override lets us preserve odd casings ("Snake Identification and Rescue")
// instead of formula-deriving everything as "{Name} Rescue and Care".
const catalog = JSON.parse(readFileSync(join(root, 'shared/species-catalog.json'), 'utf8'))
const DISPLAY_NAMES = {}
const CATEGORIES = {}
for (const sp of catalog.species) {
  if (!sp.filename) continue
  DISPLAY_NAMES[sp.filename] = sp.guide_display_name || `${sp.name} Rescue and Care`
  CATEGORIES[sp.filename] = sp.category
}

const files = readdirSync(resourcesDir).filter(f => f.endsWith('.txt')).sort()

const guides = files.map(filename => {
  const text = readFileSync(join(resourcesDir, filename), 'utf8')
  return {
    filename,
    name: DISPLAY_NAMES[filename] || filename.replace(/_/g, ' ').replace('.txt', ''),
    category: CATEGORIES[filename] || 'general',
    text,
  }
})

const ts = `// AUTO-GENERATED by workers/scripts/gen-guides.js — do not edit
// Re-run: node workers/scripts/gen-guides.js

export interface Guide {
  filename: string
  name: string
  category: string
  text: string
}

export const BUILTIN_GUIDES: Guide[] = ${JSON.stringify(guides, null, 2)}
`

const outPath = join(__dirname, '../src/guides.ts')
writeFileSync(outPath, ts)
console.log(`✓ Generated workers/src/guides.ts (${guides.length} guides, ${Math.round(guides.reduce((a, g) => a + g.text.length, 0) / 1024)}KB)`)
